# Generated by Django 4.1.2 on 2024-05-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=1000)),
                ('dadeline', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('Running', 'Running'), ('Completed', 'Completed')], max_length=30, null=True)),
                ('details', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
